### ISSUE TITLE
Errors in tests for completeness of tree B?

### ISSUE THREAD

**Issue by ryu2020** [Pingry-DS/binary-tree#1]
In the test testIsCompleteFalse1, the test asserts that tree B is incomplete, while tree B is actually complete by the standards set in the starter code.

**Comment by ryu2020** [comment]
Additionally, in testTraversePostE, the writer of the test created an iterator using tree B as opposed to tree E, causing the test to fail.

**Comment by ryu2020** [comment]
One last thing, TestTraverseInC and TestTraversePostB will both wrongly evaluate due to the fact that they compare binary tree objects to their values.
 
TestTraversePostB also wrongly refers to the BinaryTree b0 as "b".

**Comment by jorndorff** [comment]
All the traverse issues are fixed as of ab069ad9c76b2b30be1cec90068357953cf4d953

Looks like I forgot to push my last few changes. In the future, let's try to open new issues in the queue to represent actual different issues.

Thank you for reporting. I'm updating the title to reflect your concern about complete.

**Comment by jorndorff** [comment]
It looks like the definition of complete that I've used is consistent with the one provided at: https://en.wikipedia.org/wiki/Binary_tree#Types_of_binary_trees although they do state an alternate use of the word complete.

Interestingly, the definition of full that I used is NOT the same as the wikipedia page.

I guess those vocab aren't as universally defined as I had thought. Let's stick with the definitions in the comments for this assignment since most of us are done or nearly done. Glad you brought up these confusing definitions!

Thanks @ryu2020 !
